### ISSUE TITLE
NPE when getting user log events without totals

### ISSUE THREAD

**Issue by d60402** [auth0/auth0-java#118]
The following code...

    ManagementAPI mgmt = new ManagementAPI(DOMAIN, TOKEN);
    LogEventFilter filter = new LogEventFilter();
    Request<LogEventsPage> request = mgmt.users().getLogEvents("auth0|123", filter);

    try {
        LogEventsPage response = request.execute();
        ...
    } catch (Exception exception) {}

...throws a NPE...

    Exception in thread "main" java.lang.NullPointerException
        at com.fasterxml.jackson.databind.node.TreeTraversingParser.<init>(TreeTraversingParser.java:71)
        at com.fasterxml.jackson.databind.ObjectReader.treeAsTokens(ObjectReader.java:1142)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1292)
        at com.auth0.json.mgmt.logevents.LogEventsPageDeserializer.getArrayElements(LogEventsPageDeserializer.java:52)
        at com.auth0.json.mgmt.logevents.LogEventsPageDeserializer.deserialize(LogEventsPageDeserializer.java:39)
        at com.auth0.json.mgmt.logevents.LogEventsPageDeserializer.deserialize(LogEventsPageDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3011)
        at com.auth0.net.CustomRequest.parseResponse(CustomRequest.java:62)
        at com.auth0.net.BaseRequest.execute(BaseRequest.java:37)
        at com.example.Main.doAuthStuff(Main.java:37)
        at com.example.Main.main(Main.java:22)

Upon further investigation it seems that the entire structure of the data returned from APIv2 when `include_totals=true` is not passed is completely different. For example...

    GET /users/{user_id}/logs?include_totals=true

...returns a `logs` array of each event...

```
{
  "length": 4,
  "total": 4,
  "start": 0,
  "limit": 5,
  "logs": [
    {
      "date": "2018-04-19T23:31:33.947Z",
      "type": "s",
      ...
    },
    {
      "date": "2018-04-19T23:31:26.907Z",
      "type": "scp",
      ...
    },
  ...
}

```

However...

    GET /users/{user_id}/logs?include_totals=false

...returns each log event as a separate field on the returned object…

```
{
  "0": {
    "date": "2018-04-19T23:31:33.947Z",
    "type": "s",
    ...
  },
  "1": {
    "date": "2018-04-19T23:31:26.907Z",
    "type": "scp",
    ...
  },
  ...
}

```

[Zendesk Ticket](https://auth0.zendesk.com/agent/tickets/35379)

**Comment by lbalmaceda** [comment]
I've just tried this and it's already fixed. Feel free to open a new issue if another error raises.
