### ISSUE TITLE
Update username Or password using management API

### ISSUE THREAD

**Issue by shoikot** [auth0/auth0-java#46]
I'm trying to update a existing Users' username and password  with this method https://github.com/auth0/auth0-java#update

But getting a APIException and the exception description says:
```
Additional properties not allowed: identities,updated_at,created_at,family_name,given_name,nickname,name,picture,user_id 
(consider storing them in app_metadata or user_metadata. See "Users Metadata" in https://auth0.com/docs/api/v2/changes for more details)
```
I've followed this thread : https://auth0.com/forum/t/apiv2-payload-validation-error/372/4 ,  where someone named 'yenkel' said
> "I'll track this so we can add support to modify this fields in the near future, only for users that have been created in a database connection (not from any other IdP)."

that thread is old , did they implemented it , please let me know 
Question: how can I update a the username and password of existing user profile, Or how can I update that user profile ? 

Thanks in advance :)

**Comment by lbalmaceda** [comment]
Hi @shoikot,
In the same post you've linked says they [removed](https://auth0.com/forum/t/apiv2-payload-validation-error/372/10) the edition of those fields at the root level of the profile. The current way to add custom fields as of *Management API v2* is to save values in `user_metadata` using the [PATCH /v2/users](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id). With this same method you can update the `username` and `password` values if you like. Keep in mind that username and password cannot be both updated in the same call. Check that your code looks similar to this:

```java
        User updatedUser = new User("your-db-connection");
        //update either the password
        //updatedUser.setPassword("new-password");
        //or the username
        //updatedUser.setUsername("new-username");
        Map<String, Object> userMetadata = new HashMap<>();
        userMetadata.put("age", "35");
        //add more fields
        updatedUser.setUserMetadata(userMetadata);

        ManagementAPI mgmtAPI = new ManagementAPI("domain.auth0.com", "the-api-token");
        mgmtAPI.users().update("the-user-id", updatedUser).execute();
```

**Comment by eggsy84** [comment]
Trying the above example to programatically set password and it seems to fail validation.

trying something like this:

```
...
        ManagementAPI mgmt = new ManagementAPI(auth0Domain, holder.getAccessToken());

        User data = new User("Username-Password-Authentication");
        data.setPassword(password);
        mgmt.users().update(userId, data).execute();
...
```

```
com.auth0.exception.APIException: Request failed with status code 400: Payload validation error: 'None of the valid schemas were met'. Inner errors: [ Payload validation error: 'Missing required property: blocked'. (also) Payload validation error: 'Missing required property: email_verified'. (also) Payload validation error: 'Missing required property: email'. (also) Payload validation error: 'Missing required property: verify_email'. (also) Payload validation error: 'Missing required property: phone_number'. (also) Payload validation error: 'Missing required property: phone_verified'. (also) Payload validation error: 'Missing required property: verify_phone_number'. (also) Payload validation error: 'Missing required property: password'. (also) Payload validation error: 'Missing required property: verify_password'. (also) Payload validation error: 'Missing required property: user_metadata'. (also) Payload validation error: 'Missing required property: app_metadata'. (also) Payload validation error: 'Missing required property: username'. (also) Payload validation error: 'Missing required property: client_id'. ].
	at com.auth0.net.CustomRequest.createResponseException(CustomRequest.java:104)
	at com.auth0.net.CustomRequest.parseResponse(CustomRequest.java:57)
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:37)
```
