### ISSUE TITLE
BaseRequest.createRateLimitException mapping error

### ISSUE THREAD

**Issue by dmical-icims** [auth0/auth0-java#678]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-java#readme) and [Examples](https://github.com/auth0/auth0-java/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-java/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are observing the following stack trace in our production Auth0 tenant when an Auth0 management api limit is reached:

`java.lang.IllegalArgumentException: argument \"content\" is null
    at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3627)
    at com.auth0.net.BaseRequest.createRateLimitException(BaseRequest.java:225)
    at com.auth0.net.BaseRequest.createResponseException(BaseRequest.java:203)
    at com.auth0.net.BaseRequest.parseResponseBody(BaseRequest.java:84)
    at com.auth0.net.BaseRequest.execute(BaseRequest.java:139)
    at `

Here is a corresponding Auth0 log (sanitized) that triggers this error. It appears a null response is not being handled when mapping the response body.

`{
date
:
"2024-11-20T07:41:36.354Z",
type
:
"api_limit",
description
:
"Global per second organizations_read group limit has been reached",
client_id
:
"my-client-id",
client_name
:
"",
details
:
{
request
:
{
method
:
"get",
path
:
"/api/v2/organizations/{id}"
},
response
:{ }
},
log_id
:
"90020241120074136363206000000000000001223372037538618937",
tenant_name
:
"my-auth0-tenant"
}`

### Reproduction

1. trigger a rate limit event in an Auth0 tenant when making a request
2. observe error

### auth0-java version

2.12.0

### Java version

17

**Comment by dmical-icims** [comment]
Thanks for looking into this issue.

We're seeing this exception thrown consistently when the requests being sent to the following management APIs exceed the configured rate limit.

GET /api/v2/organizations/{id} with Burst Request Limit: 50 and Sustained Request Limit: 50/minute
GET /api/v2/organizations/{id}/enabled_connections with Burst Request Limit: 500 and Sustained Request Limit: 500/minute

**Comment by larsf96** [comment]
Hi @dmical-icims 
Can you post an example of your code? I've tried to reproduce it by calling this in parallel:
`mgmt.organizations().get("org_j6EWECYYl2qWrRTW").execute();`

The exception is thrown, but looking like this:
```
com.auth0.exception.RateLimitException: Request failed with status code 429: Global per second organizations_read group limit has been reached
        at com.auth0.net.BaseRequest.createRateLimitException(BaseRequest.java:226)
        at com.auth0.net.BaseRequest.createResponseException(BaseRequest.java:203)
        at com.auth0.net.BaseRequest.parseResponseBody(BaseRequest.java:84)
        at com.auth0.net.BaseRequest.execute(BaseRequest.java:139)
        at com.example.demo.TestComponent.makeAuth0Request(TestComponent.java:50)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)```

**Comment by dmical-icims** [comment]
The Auth0 management API calls are the same as your example. We're seeing the reported issue in a production environment for the following calls:

```mgmt.organizations().get(organizationId).execute();```
and
```mgmt.organizations().getConnections(organizationId, filter).execute();```

The issue started when we migrated our java service from version 8 to 17.

**Comment by tanya732** [comment]
Hi @dmical-icims,

Can you please confirm if this issue persist with all the endpoints, or specifically with organization endpoints.

**Comment by dmical-icims** [comment]
Hi @tanya732 

I checked our logs over the past 30 days and I am not seeing this issue. Previously, yes, it was only happening for organization endpoints.

**Comment by tanya732** [comment]
@dmical-icims 

We’ve looked into it internally but couldn’t trace the issue in our logs. It does appear to be specific to organization-related endpoints and hasn’t been reproducible so far.

We truly appreciate you flagging it. If the issue resurfaces or persists, please don’t hesitate to reach out—we’re more than happy to take another look.

Thank you
