### ISSUE TITLE
Issue accessing management.user().list().

### ISSUE THREAD

**Issue by Vo0Do0** [auth0/auth0-java#71]
Hi, @lbalmaceda 

I am facing one issue while accessing user's list with some parameter. I can run it from the console  but facing the issue in the sdk. Here I am attaching my code with the error message. Any help on this will be appreciated. Thanks in advance.

Code:
```java
public boolean isExistingEmail(String email){
    UserFilter filter = new UserFilter();
    filter.withFields("email", true);
    String primary = "email:".concat("\"").concat(email).concat("\"");    
    try {
      logger.info("Speciment email payload: {}", primary);
      filter.withQuery(primary);
      //filter.withQuery();
    } catch (UnsupportedEncodingException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
      return false;
    }
    logger.info("Speciment payload: {}", filter);
    Request<UsersPage> request = mgmt.users().list(filter);
    try {
        UsersPage response = request.execute();
        this.emailPresentStatus = response;
    } catch (APIException exception) {
        api error
        return false;
    } catch (Auth0Exception exception) {
        request error
      return false;
    }
    if(this.emailPresentStatus.getTotal() > 0){
      logger.info("Response while checking for email present or not {}", this.emailPresentStatus.getItems());
      return true;
    }
    return false;
}
```

Error:

```
ERROR   [2017-08-15 13:48:01,488] io.dropwizard.jersey.errors.LoggingExceptionMapper Error handling a request: 109c717ab1a127e9java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readerFor(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader;
	at com.auth0.json.mgmt.users.UsersPageDeserializer.getArrayElements(UsersPageDeserializer.java:52) ~[auth0-1.1.0.jar:na]
	at com.auth0.json.mgmt.users.UsersPageDeserializer.deserialize(UsersPageDeserializer.java:30) ~[auth0-1.1.0.jar:na]
	at com.auth0.json.mgmt.users.UsersPageDeserializer.deserialize(UsersPageDeserializer.java:15) ~[auth0-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2597) ~[jackson-databind-2.5.1.jar:2.5.1]
	at com.auth0.net.CustomRequest.parseResponse(CustomRequest.java:62) ~[auth0-1.1.0.jar:na]
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:37) ~[auth0-1.1.0.jar:na]
```

**Comment by lbalmaceda** [comment]
@Vo0Do0 The stack points to a `LoggingExceptionMapper` external to this library. Probably because that logger is trying to convert an *unknown* POJO class into a plain string for logging purposes. By commenting the `logger.info` lines the issue is fixed. For debugging purposes you can use `mgmt.setLoggingEnabled(true)` to log every http req/res, but remember to turn it off in production environments.
Also, keep in mind that you're using the `getTotals()` without telling the filter to include them first (`filter.withTotals(true)`), so that value is not coming in the response.
Cheers.
