### ISSUE TITLE
NullPointerException, StdDeserializer

### ISSUE THREAD

**Issue by LuisSaybe** [auth0/auth0-java#78]
Using `'com.auth0:auth0:1.3.0'`
java `1.8.0_111`

Failing Test:

```java
import org.junit.Test;

import com.auth0.client.mgmt.ManagementAPI;
import com.auth0.client.mgmt.filter.UserFilter;
import com.auth0.exception.Auth0Exception;
import com.auth0.json.mgmt.users.UsersPage;
import com.auth0.net.Request;

public class Auth0Test {
    @Test
    public void auth0DoesNotFail() throws Auth0Exception {
        ManagementAPI managementApi = new ManagementAPI("jivecake.auth0.com", "TOKEN_OBSCURED");
        UserFilter filter = new UserFilter();
        filter.withQuery("email:\"email@email.com\"");

        Request<UsersPage> request = managementApi.users().list(filter);
        request.execute().getItems();
    }
}
```

Stack trace:

```
java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.<init>(StdDeserializer.java:66)
	at com.auth0.json.mgmt.users.UsersPageDeserializer.<init>(UsersPageDeserializer.java:18)
	at com.auth0.json.mgmt.users.UsersPageDeserializer.<init>(UsersPageDeserializer.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:556)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.deserializerInstance(DefaultDeserializationContext.java:229)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findDeserializerFromAnnotation(DeserializerCache.java:427)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:326)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4179)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3011)
	at com.auth0.net.CustomRequest.parseResponse(CustomRequest.java:62)
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:37)
	at Auth0Test.auth0DoesNotFail(Auth0Test.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by lbalmaceda** [comment]
This seems like a json parse issue but I couldn't reproduce it with my users base. Could you please narrow the search to the user who's giving this exception and share the raw json response? Please remove any secrets/passwords/private stuff.

**Comment by LuisSaybe** [comment]
Still working to find out why this is happening, I also noticed that if I retrieve no users via `filter.withPage(0, 0);`, the same error is still thrown. The return body in this case is an empty array `[]`.

```java
 ManagementAPI managementApi = new ManagementAPI("jivecake.auth0.com", token.get("access_token").asText());
UserFilter filter = new UserFilter();
filter.withPage(0, 0);

Request<UsersPage> request = managementApi.users().list(filter);
request.execute();
```

If I clone the `1.3.0` release and run locally and run this same test, then everything works fine.

**Comment by lbalmaceda** [comment]
If I read your reply I understand that this is happening when requiring the dependency but not when cloning the repo and running this same thing along with this library project, is that correct? I've tried both ways and the result is the same, it works like expected. I can't reproduce the error you're having. If you haven't done yet, try to run the same test on a new java project with no other dependencies.

**Comment by LuisSaybe** [comment]
Turns out the problem was a transitive dependency I had to exclude
Thanks for your help

```groovy
compile('io.dropwizard:dropwizard-client:1.2.0') {
  exclude group: 'com.fasterxml.jackson.core'
}
compile('io.dropwizard:dropwizard-core:1.2.0') {
  exclude group: 'com.fasterxml.jackson.core'
}
```

**Comment by gotwalt** [comment]
Constructor chaining here is crazy here => https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/users/UsersPageDeserializer.java#L22. Jackson is calling this line with no argument and causing the superclass to throw an NPE. There should be some sort of guard here to prevent this.

**Comment by LuisSaybe** [comment]
Yes, I found the same thing too, but that works perfectly fine under the current version of Jackson in this project. What would be great is if this project upgrades to the latest version of Jackson and concurrently fixes the NPE, would resolve a lot of classpath issues

**Comment by gotwalt** [comment]
@lbalmaceda Is there a roadmap for maintenance changes to this library? If we submit a PR to fix this problem is there anything we need to do w/r/t specific testing requirements or contributor licensing?

**Comment by lbalmaceda** [comment]
Sure! submit a PR and I'll be happy to review/merge it. The only condition for me to merge it is that tests should pass. Fell free to fix the no-arg constructor (same issue applies on `LogEventsPageDeserializer` class) and to update the dependencies to latest.

**Comment by LuisSaybe** [comment]
Have the PR [here](https://github.com/auth0/auth0-java/pull/82)

**Comment by lbalmaceda** [comment]
I've just released a patch, should be already available on bintray and in a few hours on maven central.
