### ISSUE TITLE
Socket Timeout Exception while a user with large metadata attempts to login 

### ISSUE THREAD

**Issue by shoikot** [auth0/auth0-java#89]
I'm using the `v1.3.0`  and when I try to authenticate a user with large meta data then the following exception show up, the `OkHttpClient` of `AuthAPI` has a private getter so was not able set read timeout , pls have a look at following code and stack tress , any suggestion is welcome , pls suggest me how can I solve this 

**Code:**
```
public boolean authenticate(String strEmail,String strPass) {
    AuthAPI auth = new AuthAPI(domain, client_id,client_secret);
    AuthRequest request = auth.login(strEmail, strPass,auth0UserDBConnection);
            try{
                holder = request.execute();
            }catch(Auth0Exception e){
                e.printStackTrace();
                //System.out.println("Auth0 Exception::");
            } catch(Exception ex){
                ex.printStackTrace();
                //System.out.println("Exception::"+ex.getMessage());
            }
}
```
**Exception:**
```
 com.auth0.exception.Auth0Exception: Failed to execute request
	at com.auth0.net.BaseRequest.execute(BaseRequest.java:34)
	at com.test.security.Auth0Service.authenticate(Auth0Service.java:210)
	at com.test.g.LoginLayout.handleLogin(LoginLayout.java:313)
	at com.test.g.LoginLayout$1.buttonClick(LoginLayout.java:246)
	at sun.reflect.GeneratedMethodAccessor618.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.GeneratedMethodAccessor617.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.auth0.net.TelemetryInterceptor.intercept(TelemetryInterceptor.java:33)
	at okhttp3.i

```

**Comment by lbalmaceda** [comment]
Ah yes.. The OkHttpClient instance is not exposed in the public API so you won't be able to change the timeout values. How big is the metadata you're sending? This is plain text and [10 seconds](https://github.com/square/okhttp/blob/okhttp_30/okhttp/src/main/java/okhttp3/OkHttpClient.java#L350) make actually a lot of sense for common scenarios, and this is just authentication we're talking 👎 . Please, reconsider the information you're sending on every login and see if there are other ways to obtain it in a later step.

**Comment by shoikot** [comment]
@lbalmaceda thanks for the quick reply and yes we are optimizing the metadata and JSON structures so that similar issue never happen again even for the users  , so closing this ] issue
